server:
  servlet:
    context-path: /api
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/web
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-test-query: select 1
      max-lifetime: 36000
      maximum-pool-size: 50
      connection-timeout: 60000
      pool-name: main-connection-pool
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
    properties:
      hibernate:
        default_schema: curso



logging:
  level:
    org.hibernate.SLOW_QUERY: WARN
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari.HikariPool: INFO
    org.springframework.security: INFO

